package checkin.maceducation.daogenerator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CHECK_IN.
 */
public class CheckIn {

    private Long id;
    private Integer TripEaID;
    private String CheckInName;
    private String CheckInAddress;
    private String CheckInDate;
    private String Latitude;
    private String Longitude;
    private String Remark;
    private String Image;
    private Integer CheckInType;
    private Integer StatusSend;
    private Integer TripEaCustomerID;
    private Integer EnergyTypeID;
    private Double EnergyPrice;
    private Integer ActivityID;
    private String CheckInActivityRemark;
    private String CheckInActivityContact;
    private String CheckInActivityPosition;
    private String CheckInActivityEmail;
    private String CheckInActivityTel;
    private Integer SubjectID;
    private Integer EAID;

    public CheckIn() {
    }

    public CheckIn(Long id) {
        this.id = id;
    }

    public CheckIn(Long id, Integer TripEaID, String CheckInName, String CheckInAddress, String CheckInDate, String Latitude, String Longitude, String Remark, String Image, Integer CheckInType, Integer StatusSend, Integer TripEaCustomerID, Integer EnergyTypeID, Double EnergyPrice, Integer ActivityID, String CheckInActivityRemark, String CheckInActivityContact, String CheckInActivityPosition, String CheckInActivityEmail, String CheckInActivityTel, Integer SubjectID, Integer EAID) {
        this.id = id;
        this.TripEaID = TripEaID;
        this.CheckInName = CheckInName;
        this.CheckInAddress = CheckInAddress;
        this.CheckInDate = CheckInDate;
        this.Latitude = Latitude;
        this.Longitude = Longitude;
        this.Remark = Remark;
        this.Image = Image;
        this.CheckInType = CheckInType;
        this.StatusSend = StatusSend;
        this.TripEaCustomerID = TripEaCustomerID;
        this.EnergyTypeID = EnergyTypeID;
        this.EnergyPrice = EnergyPrice;
        this.ActivityID = ActivityID;
        this.CheckInActivityRemark = CheckInActivityRemark;
        this.CheckInActivityContact = CheckInActivityContact;
        this.CheckInActivityPosition = CheckInActivityPosition;
        this.CheckInActivityEmail = CheckInActivityEmail;
        this.CheckInActivityTel = CheckInActivityTel;
        this.SubjectID = SubjectID;
        this.EAID = EAID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getTripEaID() {
        return TripEaID;
    }

    public void setTripEaID(Integer TripEaID) {
        this.TripEaID = TripEaID;
    }

    public String getCheckInName() {
        return CheckInName;
    }

    public void setCheckInName(String CheckInName) {
        this.CheckInName = CheckInName;
    }

    public String getCheckInAddress() {
        return CheckInAddress;
    }

    public void setCheckInAddress(String CheckInAddress) {
        this.CheckInAddress = CheckInAddress;
    }

    public String getCheckInDate() {
        return CheckInDate;
    }

    public void setCheckInDate(String CheckInDate) {
        this.CheckInDate = CheckInDate;
    }

    public String getLatitude() {
        return Latitude;
    }

    public void setLatitude(String Latitude) {
        this.Latitude = Latitude;
    }

    public String getLongitude() {
        return Longitude;
    }

    public void setLongitude(String Longitude) {
        this.Longitude = Longitude;
    }

    public String getRemark() {
        return Remark;
    }

    public void setRemark(String Remark) {
        this.Remark = Remark;
    }

    public String getImage() {
        return Image;
    }

    public void setImage(String Image) {
        this.Image = Image;
    }

    public Integer getCheckInType() {
        return CheckInType;
    }

    public void setCheckInType(Integer CheckInType) {
        this.CheckInType = CheckInType;
    }

    public Integer getStatusSend() {
        return StatusSend;
    }

    public void setStatusSend(Integer StatusSend) {
        this.StatusSend = StatusSend;
    }

    public Integer getTripEaCustomerID() {
        return TripEaCustomerID;
    }

    public void setTripEaCustomerID(Integer TripEaCustomerID) {
        this.TripEaCustomerID = TripEaCustomerID;
    }

    public Integer getEnergyTypeID() {
        return EnergyTypeID;
    }

    public void setEnergyTypeID(Integer EnergyTypeID) {
        this.EnergyTypeID = EnergyTypeID;
    }

    public Double getEnergyPrice() {
        return EnergyPrice;
    }

    public void setEnergyPrice(Double EnergyPrice) {
        this.EnergyPrice = EnergyPrice;
    }

    public Integer getActivityID() {
        return ActivityID;
    }

    public void setActivityID(Integer ActivityID) {
        this.ActivityID = ActivityID;
    }

    public String getCheckInActivityRemark() {
        return CheckInActivityRemark;
    }

    public void setCheckInActivityRemark(String CheckInActivityRemark) {
        this.CheckInActivityRemark = CheckInActivityRemark;
    }

    public String getCheckInActivityContact() {
        return CheckInActivityContact;
    }

    public void setCheckInActivityContact(String CheckInActivityContact) {
        this.CheckInActivityContact = CheckInActivityContact;
    }

    public String getCheckInActivityPosition() {
        return CheckInActivityPosition;
    }

    public void setCheckInActivityPosition(String CheckInActivityPosition) {
        this.CheckInActivityPosition = CheckInActivityPosition;
    }

    public String getCheckInActivityEmail() {
        return CheckInActivityEmail;
    }

    public void setCheckInActivityEmail(String CheckInActivityEmail) {
        this.CheckInActivityEmail = CheckInActivityEmail;
    }

    public String getCheckInActivityTel() {
        return CheckInActivityTel;
    }

    public void setCheckInActivityTel(String CheckInActivityTel) {
        this.CheckInActivityTel = CheckInActivityTel;
    }

    public Integer getSubjectID() {
        return SubjectID;
    }

    public void setSubjectID(Integer SubjectID) {
        this.SubjectID = SubjectID;
    }

    public Integer getEAID() {
        return EAID;
    }

    public void setEAID(Integer EAID) {
        this.EAID = EAID;
    }

}
