package checkin.maceducation.daogenerator;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import checkin.maceducation.daogenerator.CheckIn;

import checkin.maceducation.daogenerator.CheckInDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig checkInDaoConfig;

    private final CheckInDao checkInDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        checkInDaoConfig = daoConfigMap.get(CheckInDao.class).clone();
        checkInDaoConfig.initIdentityScope(type);

        checkInDao = new CheckInDao(checkInDaoConfig, this);

        registerDao(CheckIn.class, checkInDao);
    }
    
    public void clear() {
        checkInDaoConfig.getIdentityScope().clear();
    }

    public CheckInDao getCheckInDao() {
        return checkInDao;
    }

}
